import type { Metadata } from "next";
import type { Viewport } from "next";

import "./globals.css";
import { poppins, sf_pro } from "@/utils/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export const viewport: Viewport =  {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sf_pro.variable} ${poppins.variable} bg-gray-800 antialiased text-white`}>{children}</body>
    </html>
  );
}
