import type { Metadata } from "next";

import "./globals.css";
import { poppins, sf_pro } from "@/utils/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sf_pro.variable} ${poppins.variable} antialiased    `}>{children}</body>
    </html>
  );
}
